### ISSUE TITLE
[Static  Assets]

### ISSUE THREAD

**Issue by nxtcoder17** [nxtcoder17/Runfile#35]

**Comment by nxtcoder17** [comment]
## Example 1

```yaml
tasks:
  example:
    cmd:
      - echo "example"
```


![Image](https://github.com/user-attachments/assets/37e33c94-bd3d-407a-8cbe-e62f6e3e2411)

**Comment by nxtcoder17** [comment]
## Example 2

```yaml
tasks:
  example:
    env:
      key: "hello world"
    cmd:
      - echo $key
```

![Image](https://github.com/user-attachments/assets/3a0979e6-53a4-4979-bc93-de6adc36fe74)

**Comment by nxtcoder17** [comment]
## Example 3

```yaml
tasks:
  example:
    env:
      key: 
        sh: echo $HOME
    cmd:
      - echo $key
```

![Image](https://github.com/user-attachments/assets/f9ca3ae6-4a49-46e4-a07b-66ba84ba14a3)

**Comment by nxtcoder17** [comment]
4. validating required environment variable

```yaml
tasks:
  example:
    env:
      key:
        required: true
    cmd:
      - echo $key
```
> [!NOTE]
> ![Image](https://github.com/user-attachments/assets/b900d81a-0eae-4ef6-ac30-8b50cf4ce292)
