### ISSUE TITLE
✨ [FEAT] something like requirements that must be satisfied for a run target

### ISSUE THREAD

**Issue by nxtcoder17** [nxtcoder17/Runfile#8]
[Here is how taskfile does this](https://taskfile.dev/usage/#ensuring-required-variables-are-set)

Example:

```yaml
version: 3

tasks:
  sample:
    requires:
      vars:
        - name
    cmds:
     - echo {{.name}}
```

![screenshot-12008](https://github.com/user-attachments/assets/7ce46820-2adb-43a5-afbe-3895b55b6e34)
